version: "3.9"

services:
  db:
    image: postgres:16
    container_name: scorer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: scorer
      POSTGRES_PASSWORD: scorer
      POSTGRES_DB: scorertest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
